org, repo = (ENV["GITHUB_REPOSITORY"] || "").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"] || "").split("/")

platform :ios do
  ########################################
  # One-time setup for Match repository
  ########################################
  lane :init_ci do
    github_action(
      api_token: ENV["GH_PAT"],
      org: org,
      repo: repo,
      match_org: match_org,
      match_repo: match_repo,
      writable_deploy_key: true
    )
  end

  ########################################
  # Use certs from match repo (readonly)
  ########################################
  lane :sync_certificates do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8"]
    )

    match(
      type: "appstore",
      storage_mode: "git",
      git_url: "git@github.com:#{match_org}/#{match_repo}.git",
      app_identifier: [ENV["IOS_BUNDLE_ID"]],
      readonly: true
    )
  end

  ########################################
  # Build + Upload to App Store Connect
  ########################################
  lane :build_and_upload do
    build
    upload_to_app_store(
      submit_for_review: false,
      automatic_release: false,
      force: true,
      skip_screenshots: true,
      run_precheck_before_submit: false
    )
  end

  ########################################
  # Build only
  ########################################
  lane :build do
    setup_ci
    sync_certificates

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_team-id"],
      code_sign_identity: "iPhone Distribution",
      targets: "Unity-iPhone",
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      profile_name: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_profile-name"],
      profile_uuid: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore"]
    )

    version_number = ENV["APP_VERSION"] || "1.0.0"
    increment_version_number(
      version_number: version_number,
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )

    increment_build_number(
      build_number: latest_testflight_build_number(
        version: version_number,
        app_identifier: ENV["IOS_BUNDLE_ID"]
      ) + 1,
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )

    build_app(
      project: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        compileBitcode: false
      }
    )
  end

  ########################################
  # Debugging & tools
  ########################################
  lane :list_profiles do
    sh "security find-identity -v -p codesigning"
  end

  lane :install_pods do
    cocoapods(
      clean: true,
      use_bundle_exec: false,
      repo_update: true,
      podfile: "#{ENV['IOS_BUILD_PATH']}/iOS/Podfile"
    )
  end
end
